from math import *
a,b=map(int,input("nhap a,b: ").split())
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(pow(a,b))
print(a%b)
if a<b : print("a nho hon b")
elif a==b : print("a bang b")
else : print("a lon hon b")
print(a and b)
print(a or b)
print(a ^ b)
print(not a == b)
print(a >> 1)
print(a << 1)